# Generated by Django 2.0.6 on 2018-07-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
