# Generated by Django 2.0.6 on 2018-07-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
    ]
