# Generated by Django 2.0.6 on 2018-07-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_song_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file_type',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
    ]
