# Generated by Django 2.0.6 on 2018-07-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='file_type',
        ),
    ]
